apiVersion: v1
kind: Pod
metadata:
  generation: 1
  labels:
    run: redis
    tier: frontend
    env: production
    release: stable
  name: redis
  namespace: default
spec:
  containers:
  - image: redis
    imagePullPolicy: Always
    name: redis-container